apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 2
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: app
        image: blackmkey/my-app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 3000
            hostPort: 3000